/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static gui.user_registration.r;
import java.io.InputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.MySQL;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MUNAFF
 */
public class product_registration extends javax.swing.JPanel {

    static String pId;

    /**
     * Creates new form product_registration
     */
    public product_registration() {
        initComponents();
        loadBrand();
        loadCategory();
        loadProduct();
    }

    public void loadProduct() {
        try {
            ResultSet rs = MySQL.search("SELECT * FROM `product`\n"
                    + "INNER JOIN `brand` ON `product`.`brand_id` = `brand`.`id`\n"
                    + "INNER JOIN `category` ON `product`.`category_id` = `category`.`id` WHERE `product_status_id`='1' ORDER BY `product`.`id` ASC");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("brand.name"));
                v.add(rs.getString("category.name"));

                dtm.addRow(v);
            }
//            jTable1.setModel(dtm);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void loadBrand() {

        try {
            ResultSet rs = MySQL.search("SELECT `name` FROM `brand`");

            Vector v = new Vector();

            v.add("Select");
            while (rs.next()) {
                v.add(rs.getString("name"));

            }

            jComboBox1.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
        }

    }

    public void loadCategory() {

        try {
            ResultSet rs = MySQL.search("SELECT `name` FROM `category`");

            Vector v = new Vector();

            v.add("Select");
            while (rs.next()) {
                v.add(rs.getString("name"));

            }

            jComboBox2.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
        }

    }

    public void resetFields() {
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jButton3.setText("Save");
        jButton4.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1600, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel1.setText("Product Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 65, 319, 39));

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel2.setText("Brand");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 60, 30));

        jComboBox1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 140, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 50, 50));

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel3.setText("Category");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, 30));

        jComboBox2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 170, 30));

        jButton2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, 50, 50));

        jButton3.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, 190, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Brand", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setPreferredSize(new java.awt.Dimension(1590, 700));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1550, 568));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 50, 20, 80));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 20, 80));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 20, 80));

        jButton4.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton4.setText("Remove");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 70, 180, 40));

        jButton5.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer_icon.png"))); // NOI18N
        jButton5.setText("Print Product List");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        brand_registration br = new brand_registration(this, true);
        br.setVisible(true);
//        BrandRegistraion1 br = new BrandRegistraion1(this, true);
//        br.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        category_registration cr = new category_registration(this, true);
        cr.setVisible(true);
//        CategoryRegistraion cr = new CategoryRegistraion(this, true);
//        cr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter product name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select the brand", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (jComboBox2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select the category", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String name = jTextField1.getText().toUpperCase();
            String brand = jComboBox1.getSelectedItem().toString();
            String category = jComboBox2.getSelectedItem().toString();
            if (jButton3.getText().equals("Update")) {
                int brandID = jComboBox1.getSelectedIndex();
                int categoryID = jComboBox2.getSelectedIndex();
                try {
                    ResultSet rsU = MySQL.search("SELECT * FROM `product` WHERE `name`='" + name + "' AND `brand_id`=" + brandID + " AND `category_id`=" + categoryID + " AND `id`<>" + pId + "");

                    if (rsU.next()) {
                        JOptionPane.showMessageDialog(this, "Product Already exists", "Warning", JOptionPane.WARNING_MESSAGE);

                    } else {
                        MySQL.iud("UPDATE `product` SET `name`='" + name + "',`brand_id`=" + brandID + ",`category_id`=" + categoryID + " WHERE `id`=" + pId + "");
                        JOptionPane.showMessageDialog(this, "ProductDetails Updated", "Warning", JOptionPane.INFORMATION_MESSAGE);
                        loadProduct();
                        resetFields();

                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }

            } else {

                try {
                    ResultSet rs = MySQL.search("SELECT * FROM `product`\n"
                            + "INNER JOIN `brand` ON `product`.`brand_id` = `brand`.`id`\n"
                            + "INNER JOIN `category` ON `product`.`category_id` = `category`.`id`\n"
                            + "WHERE `product`.`name`='" + name + "' AND `brand`.`name`='" + brand + "' AND `category`.`name`='" + category + "'");

                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Product Already exists", "Warning", JOptionPane.WARNING_MESSAGE);

                    } else {
                        try {
                            ResultSet rs1 = MySQL.search("SELECT `id` FROM `brand` WHERE `name`='" + brand + "'");
                            rs1.next();

                            ResultSet rs2 = MySQL.search("SELECT `id` FROM `category` WHERE `name`='" + category + "'");
                            rs2.next();

                            String brand_id = rs1.getString("id");
                            String category_id = rs2.getString("id");
                            long mTime = System.currentTimeMillis();

                            String uniqueId = mTime + "-" + SignIn.userId;
                            MySQL.iud("INSERT INTO `product`(`category_id`,`brand_id`,`name`,`product_no`)VALUES('" + category_id + "','" + brand_id + "','" + name + "','" + uniqueId + "')");
                            jTextField1.setText("");
                            jComboBox1.setSelectedIndex(0);
                            jComboBox2.setSelectedIndex(0);
                            JOptionPane.showMessageDialog(this, "product addedd success", "Warning", JOptionPane.WARNING_MESSAGE);
                            loadProduct();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            //      String pname =  jTextField1.getText();
            //      jComboBox1.getSelectedItem().
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {

            r = jTable1.getSelectedRow();

            if (r == -1) {
                JOptionPane.showMessageDialog(this, "Please Select a Product", "Warning", JOptionPane.WARNING_MESSAGE);

            } else {

                int option = JOptionPane.showConfirmDialog(this, "Do you want Modify Product Details?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                if (option == JOptionPane.YES_OPTION) {

                    jTextField1.setText(jTable1.getValueAt(r, 1).toString());
                    jComboBox1.setSelectedItem(jTable1.getValueAt(r, 2).toString());
                    jComboBox2.setSelectedItem(jTable1.getValueAt(r, 3).toString());
                    jButton3.setText("Update");
                    jButton4.setEnabled(true);
                    pId = jTable1.getValueAt(r, 0).toString();

                }

            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Do you want Remove Product?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        if (option == JOptionPane.YES_OPTION) {
            MySQL.iud("UPDATE `product` SET `product_status_id`='2' WHERE `id`=" + pId + "");
            loadProduct();
            resetFields();

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd  | HH:mm:ss");
        Date dToday1 = new Date();
        String dateNowN1 = sdf.format(dToday1);

        try {
            String reportUrl = "/reports/grn2.jasper";
            InputStream reportFile = null;
            reportFile = getClass().getResourceAsStream(reportUrl);
            HashMap parameters = new HashMap();

            TableModel tm = jTable1.getModel();
            JRTableModelDataSource dataSource = new JRTableModelDataSource(tm);

            JasperPrint print = JasperFillManager.fillReport(reportFile, parameters, dataSource);
            JasperViewer Jviewer = new JasperViewer(print, false);
            Jviewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
