/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static gui.product_registration.pId;
import static gui.user_registration.r;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author MUNAFF
 */
public class RegisterSuppliers extends javax.swing.JPanel {

    String supId = "0";

    /**
     * Creates new form RegisterSuppliers
     */
    public RegisterSuppliers() {
        initComponents();
        loadSupplier();
    }

    public void loadSupplier() {
        try {
            ResultSet rs = MySQL.search("SELECT *\n"
                    + "FROM `supplier`\n"
                    + "INNER JOIN `company_branch` ON `supplier`.`company_branch_id` = `company_branch`.`id`\n"
                    + "INNER JOIN `company_branch_address` ON `company_branch`.`company_branch_address_id` = `company_branch_address`.`id`\n"
                    + "INNER JOIN `city` ON `company_branch_address`.`city_id` = `city`.`id`AND `user_status_id`<>'2' ORDER BY `supplier`.`id` ASC");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("supplier.id"));
                v.add(rs.getString("supplier.name"));
                v.add(rs.getString("supplier.contact_number"));
                v.add(rs.getString("supplier.email"));
                v.add(rs.getString("company_branch.name"));
                v.add(rs.getString("company_branch.branch_contact_number"));
                v.add(rs.getString("company_branch_address.line1") + "," + rs.getString("company_branch_address.line2") + "," + rs.getString("city.name"));

                dtm.addRow(v);
            }
//            jTable1.setModel(dtm);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void resetFields() {

        jLabel8.setText("None");
        jLabel9.setText("None");
        jLabel14.setText("None");
        jLabel11.setText("None");
        jLabel12.setText("None");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jButton2.setText("Create Supplier Account");
        jButton3.setEnabled(false);
        loadSupplier();
    }

    public void check() {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        String mobile = jTextField3.getText();

        boolean isFound = false;
        int x = -1;

        for (int i = 0; i < dtm.getRowCount(); i++) {
            String s = jTable1.getValueAt(i, 2).toString();

            if (s.equals(mobile)) {
                isFound = true;
                x = i;
                break;

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1600, 850));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Supplier Name", "Contact Number", "Email", "Branch Name", "Branch Contact Number", "Branch Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1505, 350));

        jButton2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/suppliers.png"))); // NOI18N
        jButton2.setText("Create Supplier Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 530, 40));

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel3.setText("Email");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel2.setText("Contact Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel1.setText("Supplier Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        jTextField2.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 340, -1));

        jTextField3.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 340, -1));

        jTextField4.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 340, -1));

        jButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton1.setText("Select Branch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 500, 40));

        jLabel13.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel13.setText("Company Name");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jLabel14.setText("None");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 140, -1));

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel5.setText("Branch Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 21));

        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jLabel8.setText("None");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 100, -1));

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel6.setText("Branch Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, -1));

        jLabel9.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jLabel9.setText("None");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 310, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 40, 180));

        jLabel10.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel10.setText("Branch Details");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        jButton3.setText("Remove Supplier");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 340, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/resets.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 70, 200, 200));

        jLabel15.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel15.setText("Supplier Details");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel4.setText("Company Id");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel7.setText("Branch Id");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jLabel11.setText("None");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jLabel12.setText("None");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        String mobile = jTextField3.getText();

        String text = mobile + evt.getKeyChar();

        if (text.length() == 1) {

            if (!text.equals("0")) {
                evt.consume();
            }
        } else if (text.length() == 2) {

            if (!text.equals("07")) {
                evt.consume();
            }
        } else if (text.length() == 3) {

            if (!Pattern.compile("07[01245678]").matcher(text).matches()) {
                evt.consume();
            }
        } else if (text.length() <= 10) {

            if (!Pattern.compile("07[01245678][0-9]+").matcher(text).matches()) {
                evt.consume();
            }

        } else {
            evt.consume();

        }

    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String name = jTextField2.getText();
        String mobile = jTextField3.getText();
        String email = jTextField4.getText().toLowerCase();
        String bid = jLabel12.getText();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!Pattern.compile("0[0-9]{9}").matcher(mobile).matches()) {
            JOptionPane.showMessageDialog(this, "Invalid Contact Number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!Pattern.compile("[a-z0-9._%._%+-]+@[a-z0-9.]+\\.[a-z]{2,6}$").matcher(email).matches()) {
            JOptionPane.showMessageDialog(this, "Invalid Email", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (bid.equals("None")) {
            JOptionPane.showMessageDialog(this, "Please select the Branch", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            if (jButton2.getText().equals("Update Supplier Account")) {
                try {
                    ResultSet rsSupU = MySQL.search("SELECT * FROM `supplier` WHERE `id`<>'" + supId + "' AND `user_status_id`='1'");
                    if (rsSupU.next()) {
                        if (rsSupU.getString("contact_number").equals(mobile)) {
                            //        JOptionPane.showMessageDialog(this, "", "Warning", JOptionPane.WARNING_MESSAGE);
                            int option = JOptionPane.showConfirmDialog(this, "This Mobile Number is Alreay in use! Do you want Continue?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                            if (option == JOptionPane.YES_OPTION) {
                                jTextField4.grabFocus();
                                if (rsSupU.getString("email").equals(email)) {
                                    int option1 = JOptionPane.showConfirmDialog(this, "This Email is Alreay in use! Do you want Continue?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                                    if (option1 == JOptionPane.YES_OPTION) {

                                        MySQL.iud("UPDATE `supplier` SET `name`='" + name + "',`contact_number`='" + mobile + "',`email`='" + email + "',`company_branch_id`='" + bid + "' WHERE `id`='" + supId + "'");
                                        JOptionPane.showMessageDialog(this, "Supplier Details Updated", "Warning", JOptionPane.INFORMATION_MESSAGE);
                                        resetFields();
                                    }
                                }

                            } else {
                                jTextField3.setText("");

                            }
                        } else if (rsSupU.getString("email").equals(email)) {
                            int option = JOptionPane.showConfirmDialog(this, "This Email is Alreay in use! Do you want Continue?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                            if (option == JOptionPane.YES_OPTION) {
                                MySQL.iud("UPDATE `supplier` SET `name`='" + name + "',`contact_number`='" + mobile + "',`email`='" + email + "',`company_branch_id`='" + bid + "' WHERE `id`='" + supId + "'");
                                JOptionPane.showMessageDialog(this, "Supplier Details Updated", "Warning", JOptionPane.INFORMATION_MESSAGE);
                                resetFields();
                            } else {
                                jTextField4.setText("");

                            }
                        } else {

                            MySQL.iud("UPDATE `supplier` SET `name`='" + name + "',`contact_number`='" + mobile + "',`email`='" + email + "',`company_branch_id`='" + bid + "' WHERE `id`='" + supId + "'");
                            JOptionPane.showMessageDialog(this, "Supplier Details Updated", "Warning", JOptionPane.INFORMATION_MESSAGE);
                            resetFields();

                        }

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }

            } else {

                //check
                try {
                    ResultSet rs = MySQL.search("SELECT * FROM `supplier` WHERE `email`='" + email + "' OR `contact_number`='" + mobile + "'");

                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Supplier Already Exists", "Warning", JOptionPane.WARNING_MESSAGE);

                    } else {
                        MySQL.iud("INSERT INTO `supplier`(`name`,`contact_number`,`email`,`company_branch_id`)VALUES('" + name + "','" + mobile + "','" + email + "','" + bid + "')");
                        jTextField2.setText("");
                        jTextField3.setText("");
                        jTextField4.setText("");
                        jLabel12.setText("None");
                        jLabel8.setText("None");
                        jLabel9.setText("None");
                        jLabel11.setText("None");
                        jLabel14.setText("None");
                        jTextField2.grabFocus();
                        loadSupplier();
                        JOptionPane.showMessageDialog(this, "New Supplier Account Created", "Success", JOptionPane.INFORMATION_MESSAGE);

                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }

                //check
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BranchRegistration1 br = new BranchRegistration1(this, true);
        br.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {

            r = jTable1.getSelectedRow();

            if (r == -1) {
                JOptionPane.showMessageDialog(this, "Please Select a Supplier", "Warning", JOptionPane.WARNING_MESSAGE);

            } else {

                int option = JOptionPane.showConfirmDialog(this, "Do you want Modify Supplier Details?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                if (option == JOptionPane.YES_OPTION) {
                    supId = jTable1.getValueAt(r, 0).toString();
                    jTextField2.setText(jTable1.getValueAt(r, 1).toString());
                    jTextField3.setText(jTable1.getValueAt(r, 2).toString());
                    jTextField4.setText(jTable1.getValueAt(r, 3).toString());
                    jLabel8.setText(jTable1.getValueAt(r, 4).toString());
                    jLabel9.setText(jTable1.getValueAt(r, 6).toString());

                    try {
                        ResultSet rs = MySQL.search("SELECT `company`.`name`,`company_branch`.`name`,`company`.`id`,`company_branch`.`id`\n"
                                + "FROM `supplier`\n"
                                + "INNER JOIN `company_branch` ON `supplier`.`company_branch_id`= `company_branch`.`id`\n"
                                + "INNER JOIN `company` ON `company_branch`.`company_id` = `company`.`id`WHERE `supplier`.`id`='" + supId + "'");

                        if (rs.next()) {
                            jLabel14.setText(rs.getString("company.name"));
                            jLabel12.setText(rs.getString("company_branch.id"));
                            jLabel11.setText(rs.getString("company.id"));
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    jButton2.setText("Update Supplier Account");
                    jButton3.setEnabled(true);

                }

            }
        }

//        if (evt.getClickCount() == 2) {
//            int r = jTable1.getSelectedRow();
//            if (r == -1) {
//                JOptionPane.showMessageDialog(this, "Please Select a Supplier", "Warning", JOptionPane.WARNING_MESSAGE);
//
//            } else {
//
//                if (grn2 != null) {
//
//                    String sid = jTable1.getValueAt(r, 0).toString();
//
//                    String s_name = jTable1.getValueAt(r, 1).toString();
//                    String s_mobile = jTable1.getValueAt(r, 2).toString();
//                    String branch_name = jTable1.getValueAt(r, 4).toString();
//
//                    grn2.jLabel5.setText(sid);
//                    grn2.jLabel6.setText(s_name);
//                    grn2.jLabel7.setText(s_mobile);
//                    grn2.jLabel8.setText(branch_name);
//
//                    grn2.jButton1.setText("Update Supplier");
//                    grn2.jButton1.setEnabled(false);
//
//                    this.dispose();
//                }
//            }
//        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        resetFields();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Do you want Remove Supplier?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        if (option == JOptionPane.YES_OPTION) {
            MySQL.iud("UPDATE `supplier` SET `user_status_id`='2' WHERE `id`=" + supId + "");

            resetFields();

        }

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
